#!/bin/sh

msg="$(python2.7 --version 2>&1)"

MSG="$1"

echo "$MSG"

echo "Running pre-commit hook"

cat /etc/centos-release

git --version

if [[ $msg == *"command not found" ]] 
then
	python3.8 -V
	echo "Python 3.8"
	python3.8 githooks/update-modified-header.py
else
	python2.7 -V
	echo "Python 2.7"
	python2.7 githooks/update-modified-header.py
fi

echo "End of pre-commit hook"
