#!/bin/sh

msg="$(python2 --version 2>&1)"

echo "Running pre-commit hook"

if [[ $msg == *"command not found" ]] 
then
	echo "Python 3"
	python3 githooks/update-modified-header.py
else
	echo "Python 2"
	python2 githooks/update-modified-header.py
fi

echo "End of pre-commit hook"
