# This is a basic workflow to help you get started with Actions

name: trigger_kickstart

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2      

      # Runs the get changed files actions
      - name: Runs the get changed files actions               
        id: files
        uses: jitterbit/get-changed-files@v1
      
      - name: Check if 'ks.cfg' file is modified
        env: 
          fileExist: ${{ contains(steps.files.outputs.modified, 'ks.cfg') }}
        run: |
          if ${fileExist} == true; then
            echo "ks.cfg found!"
          else
            echo "ks.cfg not found!"
          fi
            
      # Runs python script
      - name: Runs python script
        run: python .github/workflows/transfer-kickstart.py
